# Generated by Django 3.0.8 on 2021-04-06 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='LabUser',
        ),
    ]
